server:
  port: ${SERVER.PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/weebook
    username: db-user
    password: db-password
    driver-class-name: org.postgresql.Driver

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://weebook-db/weebook
    username: sa
    password: PaSsWoRd123
    driver-class-name: org.postgresql.Driver